# Generated by Django 2.1.5 on 2019-09-25 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='recent_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 48, 50, 939865, tzinfo=utc)),
        ),
    ]
