# Generated by Django 2.1.5 on 2019-09-25 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='cost_basis',
            new_name='acquired_value',
        ),
        migrations.AlterField(
            model_name='investment',
            name='acquired_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='portfolio.Customer'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='investment',
            name='recent_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
