# Generated by Django 2.1.5 on 2019-10-13 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('from_number', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 13, 6, 7, 33, 11701, tzinfo=utc))),
            ],
        ),
    ]
