# Generated by Django 2.1.5 on 2019-09-25 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='acquired_value',
        ),
        migrations.AddField(
            model_name='investment',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2019, 9, 25, 4, 34, 46, 566050, tzinfo=utc), max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='acquired_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='portfolio.Customer'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='investment',
            name='recent_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 32, 47, 650571, tzinfo=utc)),
        ),
    ]
