# Generated by Django 2.1.5 on 2019-10-16 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 16, 0, 13, 53, 595644, tzinfo=utc)),
        ),
    ]
