# Generated by Django 2.1.5 on 2019-10-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191015_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='date',
        ),
    ]
